# -*- coding: utf-8 -*-
"""extension_task2_langgraph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2CLRZ5A2nONfC-Vm26wX6r-VpqGOrzK
"""

!pip install -q langgraph langchain langchain-groq duckduckgo-search

import warnings
warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)



# IMPORTS

from dataclasses import dataclass
from enum import Enum
from typing import Optional, TypedDict

from langgraph.graph import StateGraph, END


# ENUM

class ReviewDecision(Enum):
    APPROVE = "approve"
    REJECT = "reject"
    ESCALATE = "escalate"

# DATA MODEL

@dataclass
class LoanRequest:
    application_id: str
    loan_amount: float
    applicant_summary: str
    ai_recommendation: str
    risk_score: float
    review_required: bool = False
    human_decision: Optional[ReviewDecision] = None
    reviewer_id: Optional[str] = None
    review_notes: Optional[str] = None


# STATE

class LoanState(TypedDict):
    request: LoanRequest
    route: str
    output: dict


# PLANNER NODE

def planner_node(state: LoanState) -> LoanState:
    req = state["request"]

    HIGH_VALUE = 1_000_000
    HIGH_RISK = 0.7

    if req.loan_amount >= HIGH_VALUE or req.risk_score >= HIGH_RISK:
        route = "human_review"
        req.review_required = True
    else:
        route = "auto_process"

    return {**state, "route": route, "request": req}


# AUTO PROCESS NODE

def auto_process_node(state):
    req = state["request"]
    req.human_decision = ReviewDecision.APPROVE
    return {**state, "request": req}


# HUMAN REVIEW NODE

def human_review_node(state):
    req = state["request"]

    decision = ReviewDecision.APPROVE if req.risk_score < 0.7 else ReviewDecision.REJECT

    req.human_decision = decision
    req.review_notes = "HITL completed"

    return {**state, "request": req}


# FORMATTER NODE

def formatter_node(state: LoanState):
    req = state["request"]

    return {
        "output": {
            "application_id": req.application_id,
            "loan_amount": req.loan_amount,
            "risk_score": req.risk_score,
            "route": state["route"],
            "decision": req.human_decision.value if req.human_decision else "APPROVE"
        }
    }


# ROUTER

def router(state: LoanState):
    return state["route"]


# BUILD GRAPH

graph = StateGraph(LoanState)

graph.add_node("planner", planner_node)
graph.add_node("auto_process", auto_process_node)
graph.add_node("human_review", human_review_node)
graph.add_node("formatter", formatter_node)

graph.set_entry_point("planner")

graph.add_conditional_edges("planner", router)

graph.add_edge("auto_process", "formatter")
graph.add_edge("human_review", "formatter")
graph.add_edge("formatter", END)

app = graph.compile()


# TEST DATA

test_loans = [
    LoanRequest('APP100301', 500_000,   'Salaried, credit score 720', 'Likely approve', 0.25),
    LoanRequest('APP100302', 1_500_000, 'Self-employed, credit score 660', 'Borderline', 0.62),
    LoanRequest('APP100303', 200_000,   'Salaried, credit score 580', 'High risk', 0.82),
    LoanRequest('APP100304', 800_000,   'Salaried, credit score 750', 'Likely approve', 0.18),
]

# RUN (CLEAN OUTPUT ONLY)

print("\n LANGGRAPH + PLANNER + HITL SYSTEM ")
print("-" * 70)

for loan in test_loans:

    result = app.invoke({"request": loan})

    out = result["output"]

    print("\n" + "=" * 60)
    print(f" ID      : {out['application_id']}")
    print(f" AMOUNT  : ₹{out['loan_amount']:,.0f}")
    print(f" RISK    : {out['risk_score']}")
    print(f" ROUTE   : {out['route']}")
    print(f" DECISION: {out['decision']}")
    print("=" * 60)