# -*- coding: utf-8 -*-
"""Smart_FAQ_Bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QHiB8IbWO8eK9ZrwNbDnZBdlsSLjPCO
"""

!pip install -q gradio groq langchain-community faiss-cpu sentence-transformers

import gradio as gr
from groq import Groq
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_core.documents import Document

# -------------------------
# Add your NEW Groq API Key
# -------------------------
GROQ_API_KEY = ""

client = Groq(api_key=GROQ_API_KEY)

# -------------------------
# FAQ Dataset
# -------------------------
faqs = [
    "To reset your password, click 'Forgot Password' on the login page.",
    "To enroll in a course, click the Enroll button on the course page.",
    "Course videos cannot be downloaded.",
    "Certificates are issued after successful course completion.",
    "We accept Credit Card, Debit Card, UPI and Net Banking.",
    "Refunds are available within 7 days of purchase.",
    "Customer support is available via email and live chat.",
    "Courses are accessible on mobile devices.",
    "You can change your registered email address in account settings.",
    "Purchased courses have lifetime access."
]

# -------------------------
# Build FAISS Index
# -------------------------
docs = [Document(page_content=faq) for faq in faqs]

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vectorstore = FAISS.from_documents(docs, embeddings)

# -------------------------
# Bot Function
# -------------------------
def faq_bot(query):

    if not query.strip():
        return "Please enter a question."

    try:
        # Retrieve top 2 FAQs
        results = vectorstore.similarity_search_with_score(
            query,
            k=2
        )

        context = "\n".join(
            [doc.page_content for doc, score in results]
        )

        prompt = f"""
                You are a FAQ assistant.

                Use ONLY the FAQ information below.

                FAQ Context:
                {context}

                Question:
                {query}

                Give a short answer.
                """

        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0
        )

        answer = response.choices[0].message.content

        scores = "\n".join(
            [
                f"• {doc.page_content} | Score={score:.4f}"
                for doc, score in results
            ]
        )

        return f"{answer}\n\nTop Matches:\n{scores}"

    except Exception as e:
        return f"Error: {str(e)}"

# -------------------------
# Exit Function
# -------------------------
def exit_app():
    return "Session Ended. You may close this browser tab."

# -------------------------
# Gradio UI
# -------------------------
with gr.Blocks() as demo:

    gr.Markdown("# Smart FAQ Bot")
    gr.Markdown("Ask any question related to the FAQs")

    query = gr.Textbox(
        label="Question",
        placeholder="Type your question..."
    )

    output = gr.Textbox(
        label="Answer",
        lines=12
    )

    with gr.Row():
        ask_btn = gr.Button("Ask")
        clear_btn = gr.Button("Clear")
        exit_btn = gr.Button("Exit")

    ask_btn.click(
        faq_bot,
        inputs=query,
        outputs=output
    )

    clear_btn.click(
        lambda: ("", ""),
        outputs=[query, output]
    )

    exit_btn.click(
        exit_app,
        outputs=output
    )

demo.launch(
    share=True,
    debug=True
)

