# -*- coding: utf-8 -*-
"""Colab2_Capstone_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCLAi_N2BEt5I_TrE5xhISwVaQ15vYu8

# Day 18 · Colab 2 — Multi-tool Agent Chaining + Redis Event Queue

**Agentic Systems Bootcamp**

Here the agent does real **orchestration**: it *chains* tools to place an order —
`check_inventory → create_order → send_confirmation` — mixing **synchronous** tools
(SQLite reads/writes) with an **asynchronous** one (enqueue an email job onto a Redis Stream,
handled later by a separate **worker** via a consumer group).

Runs entirely in Colab: `fakeredis` provides `XADD` / `XREADGROUP`, SQLite is built in.

> **Patterns (from the deck):** *routing* (pick the right tool), *prompt chaining* (feed one tool's
> output into the next), *parallel* reads, and the **sync-vs-async** boundary — slow side-effects go
> on a queue so the agent turn stays fast.

## Step 1 — Install & configure
"""

!pip install -q anthropic fakeredis 2>/dev/null
import os, getpass
if not os.environ.get('ANTHROPIC_API_KEY'):
    try:
        from google.colab import userdata
        os.environ['ANTHROPIC_API_KEY'] = userdata.get('ANTHROPIC_API_KEY')
    except Exception:
        pass
if not os.environ.get('ANTHROPIC_API_KEY'):
    os.environ['ANTHROPIC_API_KEY'] = getpass.getpass('ANTHROPIC_API_KEY (blank = offline mock): ')
LIVE = bool(os.environ.get('ANTHROPIC_API_KEY'))
MODEL = 'claude-sonnet-4-6'
print('LIVE mode' if LIVE else 'OFFLINE mock mode')

"""## Step 2 — SQLite orders + inventory database

Two tables: `inventory` (stock per SKU) and `orders` (what we create).
All access is through **parameterised** SQL — never string-formatted — and reads are row-limited.
"""

import sqlite3
db = sqlite3.connect(':memory:', check_same_thread=False)
db.execute('CREATE TABLE inventory (sku TEXT PRIMARY KEY, name TEXT, qty INTEGER, price REAL)')
db.execute('CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT, sku TEXT, qty INTEGER, total REAL, status TEXT)')
db.executemany('INSERT INTO inventory VALUES (?,?,?,?)', [
    ('KB-01', 'Mechanical keyboard', 12, 129.0),
    ('HUB-2', 'USB-C hub',           0,  58.0),
    ('MON-4', '4K monitor',          5, 410.0),
])
db.commit()
print('inventory seeded')

"""## Step 3 — A Redis Stream as the email job queue

`send_confirmation` won't send email inline (slow, can fail). It **enqueues** a job with `XADD` and
returns a `job_id` immediately. A **worker** later reads with `XREADGROUP` (a consumer group gives us
at-least-once delivery + acks) and writes the result back to a `jobresult:<id>` key.
"""

import fakeredis, json, time, uuid
r = fakeredis.FakeStrictRedis()
STREAM = 'emails'
GROUP  = 'mailers'
try:
    r.xgroup_create(STREAM, GROUP, id='0', mkstream=True)
except Exception as e:
    print('group exists:', e)

def enqueue_email(to, subject, body):
    job_id = uuid.uuid4().hex[:8]
    r.xadd(STREAM, {'job_id': job_id, 'to': to, 'subject': subject, 'body': body})
    r.set(f'jobresult:{job_id}', 'queued')
    return job_id

print('queue ready; sample job id ->', enqueue_email('a@x.com', 'hi', 'test'))

"""## Step 4 — The worker (consumer group)

In production this is a separate process. Here we drain the stream on demand. Each message is
processed, the result stored, and the message **acked** with `XACK` so it isn't redelivered.
"""

def run_worker(max_msgs=10):
    processed = 0
    resp = r.xreadgroup(GROUP, 'worker-1', {STREAM: '>'}, count=max_msgs)
    for _stream, msgs in resp or []:
        for msg_id, fields in msgs:
            f = {k.decode(): v.decode() for k, v in fields.items()}
            # … here you'd call a real email provider …
            r.set(f"jobresult:{f['job_id']}", 'sent')
            r.xack(STREAM, GROUP, msg_id)
            processed += 1
    return processed

print('worker processed', run_worker(), 'job(s)')

"""## Step 5 — Tool functions (sync + async)

`check_inventory` and `create_order` are **synchronous** — they touch SQLite and return immediately.
`create_order` re-checks stock and decrements it in one transaction (guarding against overselling).
`send_confirmation` is **asynchronous** — it enqueues and returns a `job_id`. `check_job` polls a result.
"""

def check_inventory(sku: str):
    row = db.execute('SELECT sku,name,qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not row:
        return {'error': f'unknown sku {sku}'}
    return {'sku': row[0], 'name': row[1], 'qty': row[2], 'price': row[3]}

def create_order(sku: str, qty: int):
    cur = db.execute('SELECT qty,price FROM inventory WHERE sku=? LIMIT 1', (sku,)).fetchone()
    if not cur:
        return {'error': f'unknown sku {sku}'}
    have, price = cur
    if qty <= 0:
        return {'error': 'qty must be positive'}
    if have < qty:
        return {'error': f'insufficient stock: have {have}, need {qty}'}
    db.execute('UPDATE inventory SET qty=qty-? WHERE sku=?', (qty, sku))
    cur2 = db.execute('INSERT INTO orders (sku,qty,total,status) VALUES (?,?,?,?)',
                      (sku, qty, round(price*qty, 2), 'created'))
    db.commit()
    return {'order_id': cur2.lastrowid, 'sku': sku, 'qty': qty, 'total': round(price*qty, 2)}

def send_confirmation(to: str, order_id: int):
    job_id = enqueue_email(to, f'Order {order_id} confirmed', f'Your order {order_id} is on its way.')
    return {'job_id': job_id, 'status': 'queued'}

def check_job(job_id: str):
    v = r.get(f'jobresult:{job_id}')
    return {'job_id': job_id, 'status': v.decode() if v else 'unknown'}

# quick manual chain
inv = check_inventory('KB-01'); print(inv)
od  = create_order('KB-01', 2);  print(od)
jb  = send_confirmation('asha@x.com', od['order_id']); print(jb)
run_worker(); print(check_job(jb['job_id']))

"""## Step 6 — Tool schemas + dispatch"""

TOOLS = [
  {'name':'check_inventory','description':'Check stock and price for a product SKU before ordering.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string','description':'Product SKU, e.g. KB-01.'}},'required':['sku']}},
  {'name':'create_order','description':'Create an order for a SKU and quantity. Fails if stock is insufficient.',
   'input_schema':{'type':'object','properties':{'sku':{'type':'string'},'qty':{'type':'integer','description':'Units to order (>0).'}},'required':['sku','qty']}},
  {'name':'send_confirmation','description':'Queue a confirmation email for a created order. Returns a job_id immediately.',
   'input_schema':{'type':'object','properties':{'to':{'type':'string','description':'Customer email.'},'order_id':{'type':'integer'}},'required':['to','order_id']}},
  {'name':'check_job','description':'Check the status of a queued email job by job_id.',
   'input_schema':{'type':'object','properties':{'job_id':{'type':'string'}},'required':['job_id']}},
]
DISPATCH = {'check_inventory':check_inventory,'create_order':create_order,
            'send_confirmation':send_confirmation,'check_job':check_job}

def run_tool(name, args):
    fn = DISPATCH.get(name)
    if not fn: return {'error': f'unknown tool {name}'}, True
    try:
        out = fn(**args)
        return out, isinstance(out, dict) and 'error' in out
    except Exception as e:
        return {'error': repr(e)}, True
print('tools ready')

"""## Step 7 — The orchestrating agent loop

Same `stop_reason` loop as Colab 1, but now the model **chains** several tools in one turn and we
drain the worker afterwards. The offline mock scripts the full chain so the notebook runs without a key.
"""

import json
SYSTEM = (
  'You are an ordering agent. To place an order: first check_inventory, then create_order, '
  'then send_confirmation with the returned order_id. Report the order total and the email job status. '
  'If stock is insufficient, say so and do not create the order.'
)

def agent(user_text, max_steps=8, verbose=True):
    if not LIVE:
        if verbose: print('… (mock) chaining check_inventory → create_order → send_confirmation')
        inv,_ = run_tool('check_inventory', {'sku':'MON-4'})
        od,_  = run_tool('create_order', {'sku':'MON-4','qty':1})
        jb,_  = run_tool('send_confirmation', {'to':'asha@x.com','order_id':od['order_id']})
        run_worker()
        st,_  = run_tool('check_job', {'job_id':jb['job_id']})
        return f"(mock) Order {od['order_id']} total ${od['total']}; email {st['status']}."

    from anthropic import Anthropic
    A = Anthropic()
    messages = [{'role':'user','content':user_text}]
    for _ in range(max_steps):
        resp = A.messages.create(model=MODEL, max_tokens=1024, system=SYSTEM, tools=TOOLS, messages=messages)
        if resp.stop_reason == 'tool_use':
            messages.append({'role':'assistant','content':[b.model_dump() for b in resp.content]})
            results = []
            for b in resp.content:
                if b.type == 'tool_use':
                    if verbose: print(f'  → {b.name}({b.input})')
                    out, is_err = run_tool(b.name, b.input)
                    results.append({'type':'tool_result','tool_use_id':b.id,
                                    'content':json.dumps(out),'is_error':is_err})
            messages.append({'role':'user','content':results})
            run_worker()  # drain any queued email jobs between steps
            continue
        return ''.join(b.text for b in resp.content if b.type=='text')
    return '(max steps reached)'

print(agent('Order one 4K monitor (SKU MON-4) and email asha@x.com the confirmation.'))

"""## Step 8 — Show the resulting state"""

print('Orders table:')
for row in db.execute('SELECT id,sku,qty,total,status FROM orders').fetchall():
    print(' ', row)
print('Remaining stock:')
for row in db.execute('SELECT sku,qty FROM inventory').fetchall():
    print(' ', row)
# Try an out-of-stock order to see graceful failure
print('Out-of-stock attempt:', run_tool('create_order', {'sku':'HUB-2','qty':1}))

"""## Extension tasks

1. **Dead-letter & retry.** Make the worker fail jobs whose `to` is invalid; move them to an `emails:dlq`
   stream after N retries instead of acking. Add a tool to inspect the DLQ.
2. **Evaluator / verify step.** Add a `verify_order` tool that re-reads the order and confirms total &
   status; have the system prompt require it before declaring success (evaluator-optimiser pattern).
3. **Orchestrator-worker split.** Move `run_worker()` into a background `threading.Thread` loop so the
   agent never calls it directly; the queue truly decouples them.
4. **Human-in-the-loop gate.** For orders above a value threshold, have `create_order` return
   `{'status':'needs_approval'}` and require an `approve_order(order_id)` tool call before fulfilment.
5. **Trace spans.** Wrap `run_tool` to record `{tool, args, ms, ok}` per call; print a per-turn trace table.
6. **Prompt caching + token savings.** Mark the system prompt and tool block as cache-eligible and compare
   `usage.cache_read_input_tokens` across two identical turns; report the measured savings.

> **Stretch:** replace `fakeredis` with a real Redis (`redis.Redis.from_url(os.environ['REDIS_URL'])`) and
> run the worker as a genuinely separate Colab cell / process. The stream + consumer-group code is identical.

#capstone task
"""

!pip install -q redis fakeredis faiss-cpu sentence-transformers

import fakeredis
import faiss
import numpy as np
import hashlib
import time

from sentence_transformers import SentenceTransformer

# ==================================================
# REDIS SHORT TERM MEMORY
# ==================================================

redis_client = fakeredis.FakeRedis()

def save_chat(session, role, msg):
    redis_client.rpush(
        f"chat:{session}",
        f"{role}: {msg}"
    )

def get_chat(session):
    msgs = redis_client.lrange(
        f"chat:{session}",
        0,
        -1
    )
    return [m.decode() for m in msgs]

# ==================================================
# VECTOR STORE LONG TERM MEMORY
# ==================================================

embedder = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

dimension = 384
index = faiss.IndexFlatL2(dimension)

memory_docs = []

def store_memory(text):

    vec = embedder.encode([text]).astype("float32")

    index.add(vec)

    memory_docs.append(text)

def recall_memory(query,k=3):

    if len(memory_docs)==0:
        return []

    vec = embedder.encode([query]).astype("float32")

    D,I = index.search(vec,k)

    results=[]

    for idx in I[0]:
        if idx < len(memory_docs):
            results.append(memory_docs[idx])

    return results

# ==================================================
# PROMPT CACHE
# ==================================================

cache = {}

def get_cache(prompt):

    key = hashlib.md5(
        prompt.encode()
    ).hexdigest()

    return cache.get(key)

def set_cache(prompt,response):

    key = hashlib.md5(
        prompt.encode()
    ).hexdigest()

    cache[key] = response

# ==================================================
# TRACE LOGGING
# ==================================================

trace_logs=[]

def trace(msg):

    trace_logs.append(msg)

    print(f"[TRACE] {msg}")

# ==================================================
# RETRIES
# ==================================================

def retry(func,*args,retries=3):

    for attempt in range(retries):

        try:
            return func(*args)

        except Exception as e:

            print(
                f"Retry {attempt+1}: {e}"
            )

            time.sleep(1)

    raise Exception(
        "Max retries exceeded"
    )

# ==================================================
# TOOL 1 - ORDER STATUS
# ==================================================

orders = {
    101:"Processing",
    102:"Shipped",
    103:"Delivered"
}

def order_status(order_id):

    return orders.get(
        order_id,
        "Order Not Found"
    )

# ==================================================
# TOOL 2 - FAQ TOOL
# ==================================================

faq_db = {
    "refund":
    "Refund takes 5 business days",

    "shipping":
    "Shipping takes 3 business days",

    "payment":
    "Payment accepted via cards and UPI"
}

def faq_tool(question):

    q = question.lower()

    for k,v in faq_db.items():

        if k in q:
            return v

    return "FAQ Not Found"

# ==================================================
# TOOL 3 - ASYNC EMAIL TOOL
# ==================================================

EMAIL_QUEUE = "email_queue"

def send_email_async(
    email,
    message
):

    redis_client.xadd(
        EMAIL_QUEUE,
        {
            "email":email,
            "message":message
        }
    )

    return "Email Queued"

# ==================================================
# ASYNC WORKER
# ==================================================

def email_worker():

    jobs = redis_client.xrange(
        EMAIL_QUEUE
    )

    print("\nEMAIL WORKER\n")

    for _,job in jobs:

        print(
            f"Email sent to "
            f"{job[b'email'].decode()}"
        )

# ==================================================
# HUMAN APPROVAL GATE
# ==================================================

def approve_refund(order_id):

    approval = input(
        f"Approve refund for Order {order_id}? (yes/no): "
    )

    if approval.lower()!="yes":

        return "Refund Rejected"

    return "Refund Approved"

# ==================================================
# ROUTER
# ==================================================

def router(query):

    q = query.lower()

    if "order" in q:
        return "order"

    elif "refund" in q:
        return "refund"

    elif "email" in q:
        return "email"

    else:
        return "faq"

# ==================================================
# MAIN AGENT
# ==================================================

def support_agent(
    session_id,
    query
):

    cached = get_cache(query)

    if cached:

        trace("CACHE HIT")

        return cached

    trace("CACHE MISS")

    save_chat(
        session_id,
        "user",
        query
    )

    memories = recall_memory(query)

    trace(
        f"MEMORIES: {memories}"
    )

    intent = router(query)

    trace(
        f"ROUTED TO: {intent}"
    )

    if intent=="order":

        result = retry(
            order_status,
            102
        )

    elif intent=="refund":

        result = approve_refund(
            102
        )

        if "Approved" in result:

            send_email_async(
                "customer@test.com",
                "Refund processed"
            )

    elif intent=="email":

        result = send_email_async(
            "customer@test.com",
            query
        )

    else:

        result = faq_tool(query)

    save_chat(
        session_id,
        "assistant",
        str(result)
    )

    store_memory(query)

    set_cache(
        query,
        result
    )

    return result

# ==================================================
# DEMO
# ==================================================

print("\n--- ORDER QUERY ---")
print(
    support_agent(
        "session1",
        "Where is my order?"
    )
)

print("\n--- REFUND QUERY ---")
print(
    support_agent(
        "session1",
        "I want refund"
    )
)

print("\n--- EMAIL QUERY ---")
print(
    support_agent(
        "session1",
        "send email confirmation"
    )
)

print("\n--- FAQ QUERY ---")
print(
    support_agent(
        "session1",
        "shipping information"
    )
)

print("\n--- CHAT HISTORY ---")
print(
    get_chat("session1")
)

email_worker()

"""┌─────────────────┐
                         │      USER       │
                         └────────┬────────┘
                                  │
                                  ▼
                    ┌──────────────────────────┐
                    │     SUPPORT AGENT        │
                    │ (Routing + Chaining)     │
                    └──────────┬───────────────┘
                               │
          ┌────────────────────┼────────────────────┐
          │                    │                    │
          ▼                    ▼                    ▼

 ┌────────────────┐  ┌────────────────┐  ┌────────────────┐
 │ Redis STM      │  │ Vector Store   │  │ Prompt Cache   │
 │ Short-Term Mem │  │ Long-Term Mem  │  │ Cached Replies │
 └────────────────┘  └────────────────┘  └────────────────┘

                               │
                               ▼
                     ┌─────────────────┐
                     │ Intent Router   │
                     └────────┬────────┘
                              │
      ┌───────────────────────┼─────────────────────────┐
      │                       │                         │
      ▼                       ▼                         ▼

┌──────────────┐      ┌──────────────┐        ┌──────────────┐
│ Order Tool   │      │ FAQ Tool     │        │ Email Tool   │
│ Status Check │      │ Knowledge    │        │ Async Queue  │
└──────────────┘      └──────────────┘        └──────┬───────┘
                                                     │
                                                     ▼

                                           ┌────────────────┐
                                           │ Redis Queue    │
                                           └──────┬─────────┘
                                                  │
                                                  ▼

                                           ┌────────────────┐
                                           │ Email Worker   │
                                           └────────────────┘

                              │
                              ▼

                    ┌──────────────────┐
                    │ Human Approval   │
                    │ Refund Requests  │
                    └────────┬─────────┘
                             │
                             ▼

                    ┌──────────────────┐
                    │ Retry + Tracing  │
                    └──────────────────┘

## Short Architecture Notes:
1. User Interaction
User submits a support-related query.
Query is received by the Support Agent.
2. Short-Term Memory (Redis)
Redis stores conversation history for the current session.
Helps the agent maintain context across multiple messages.
3. Long-Term Memory (FAISS Vector Store)
User queries are converted into embeddings.
FAISS stores and retrieves semantically similar past interactions.
Enables long-term recall.
4. Prompt Cache
Checks whether the same query was previously processed.
Returns cached response if available.
Reduces latency and repeated computation.
5. Intent Routing
Agent analyzes the query intent.
Routes requests to the appropriate tool.
Supported intents:
Order Status
Refund Request
FAQ Query
Email Request
6. Tool Layer
Order Status Tool: Retrieves order information.
FAQ Tool: Answers common customer questions.
Email Tool: Sends notifications asynchronously.
7. Async Queue Processing
Email requests are pushed into a Redis Queue.
Separate Email Worker processes queued jobs.
Prevents blocking the main agent workflow.
8. Tool Chaining
Multiple tools can be executed sequentially.
Example:
Refund Request
Human Approval
Email Notification
9. Human Approval Gate
Refund actions require manual approval.
Prevents unauthorized automated actions.
Implements Human-in-the-Loop (HITL).
10. Retry Mechanism
Failed tool executions are automatically retried.
Improves system reliability and fault tolerance.
11. Tracing & Monitoring
Logs key events such as:
Request received
Routing decision
Tool execution
Response generated
Helps debugging and observability.
"""

