# -*- coding: utf-8 -*-
"""pull_push_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tJsbPykModr1JUlA1iAyAv_FdKmuKmIb

# Pull vs Push Notification Architecture


- **Pull**: client polls `GET /notifications` on a fixed interval.
- **Push**: server emits a WebSocket event to connected clients instantly.

## 0. Install dependencies
"""

!pip install -q flask flask-socketio "python-socketio[client]" requests

"""## 1. Pull demo — start the server (background thread)

The server keeps notifications in an in-memory list and is seeded with one
welcome message so the first poll has something to return.
"""

import threading, time
from datetime import datetime
from flask import Flask, jsonify, request

pull_app = Flask("pull_server")
notifications = []
_next_id = 1

def add_notification(message):
    global _next_id
    note = {
        "id": _next_id,
        "message": message,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
    }
    notifications.append(note)
    _next_id += 1
    return note

# Seed one welcome notification.
add_notification("Welcome! No new updates yet.")

@pull_app.route("/notifications", methods=["GET"])
def get_notifications():
    try:
        after_id = int(request.args.get("after_id", 0))
    except ValueError:
        after_id = 0
    return jsonify([n for n in notifications if n["id"] > after_id])

@pull_app.route("/add", methods=["POST"])
def add():
    data = request.get_json(silent=True) or {}
    message = data.get("message")
    if not message:
        return jsonify({"error": "Field 'message' is required."}), 400
    return jsonify({"status": "added", "notification": add_notification(message)}), 201

def run_pull_server():
    # use_reloader=False is required when running inside a thread.
    pull_app.run(host="127.0.0.1", port=5000, debug=False, use_reloader=False)

threading.Thread(target=run_pull_server, daemon=True).start()
time.sleep(2)
print("Pull server running on http://127.0.0.1:5000")

"""## 2. Pull demo — the client

A real client polls forever. In a notebook an infinite loop would hang the
cell, so this version polls a **fixed number of cycles**. To make the demo
self-contained it also adds a notification partway through, so you can watch a
new item appear on the next poll.
"""

import requests

POLL_INTERVAL = 5   # seconds, matches the project description
CYCLES = 4          # bounded so the cell finishes

last_seen_id = 0
print(f"Polling for notifications every {POLL_INTERVAL} seconds...\n")

for cycle in range(CYCLES):
    # Halfway through, add a notification to simulate an external event.
    if cycle == 2:
        requests.post("http://127.0.0.1:5000/add",
                      json={"message": "Support ticket updated"})

    new_notes = requests.get(
        "http://127.0.0.1:5000/notifications",
        params={"after_id": last_seen_id},
        timeout=10,
    ).json()

    if new_notes:
        for note in new_notes:
            print(f"[NEW] {note['id']} - {note['message']} ({note['timestamp']})")
            last_seen_id = max(last_seen_id, note["id"])
    else:
        print("No new notifications.")

    time.sleep(POLL_INTERVAL)

print("\nDone polling.")

"""## 3. Add your own notification (optional)

Run this any time after the server is up, then re-run the polling cell above
(reset `last_seen_id = 0` first if you want to see everything again).
"""

r = requests.post("http://127.0.0.1:5000/add",
                  json={"message": "A manually added notification"})
print(r.json())

"""---
## 4. Push demo — start the SocketIO server (background thread)

`async_mode="threading"` keeps dependencies minimal. `allow_unsafe_werkzeug=True`
lets the built-in dev server run for this local demo (not for production).
"""

from flask import Flask as _Flask
from flask_socketio import SocketIO

push_app = _Flask("push_server")
push_app.config["SECRET_KEY"] = "push-demo-secret"
socketio = SocketIO(push_app, cors_allowed_origins="*", async_mode="threading")

def _ts():
    return datetime.now().isoformat(timespec="seconds")

@socketio.on("connect")
def handle_connect():
    socketio.emit("notification",
                  {"message": "Connected to push server", "timestamp": _ts()})

@push_app.route("/trigger", methods=["POST"])
def trigger():
    data = request.get_json(silent=True) or {}
    message = data.get("message")
    if not message:
        return jsonify({"error": "Field 'message' is required."}), 400
    payload = {"message": message, "timestamp": _ts()}
    socketio.emit("notification", payload)          # broadcast to all clients
    return jsonify({"status": "pushed", "notification": payload})

def run_push_server():
    socketio.run(push_app, host="127.0.0.1", port=5001,
                 debug=False, allow_unsafe_werkzeug=True)

threading.Thread(target=run_push_server, daemon=True).start()
time.sleep(3)
print("Push server running on http://127.0.0.1:5001")

"""## 5. Push demo — connect the client

`python-socketio`'s `Client` runs its own background thread, so we do **not**
call `sio.wait()` (which would hang the cell). The client stays connected and
its handler fires whenever the server pushes an event.
"""

import socketio as sioclient

sio = sioclient.Client()

@sio.event
def connect():
    print("Connected to push server")

@sio.event
def disconnect():
    print("Disconnected from push server")

@sio.on("notification")
def on_notification(data):
    print(f"[PUSH RECEIVED] {data.get('message','')} ({data.get('timestamp','')})")

sio.connect("http://127.0.0.1:5001")
time.sleep(1)   # give the welcome push time to arrive
print("Client is listening...")

"""## 6. Trigger a push

Run this cell — the message arrives at the client **instantly** (look for
`[PUSH RECEIVED]` printed above from the listening client). Run it as many
times as you like.
"""

r = requests.post("http://127.0.0.1:5001/trigger",
                  json={"message": "Your support ticket has been resolved"})
print(r.json())
time.sleep(1)   # let the pushed event print before the cell ends

"""## 7. Disconnect the push client (optional)

---
## Notes for Colab

- **Servers run in threads, not separate processes**, because a notebook has a
  single kernel and no extra terminals.
- **Clients are bounded** (fixed poll count for pull; no `sio.wait()` for push)
  so cells finish instead of hanging.
- **`127.0.0.1` works** because client and server live in the same Colab VM.
  These ports are *not* reachable from your laptop's browser — that's expected.
- If you re-run a server cell and get an *"address already in use"* error, use
  **Runtime → Restart runtime** and run the cells again.
"""