# -*- coding: utf-8 -*-
"""skill_md_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JUC6o6P4Z6phmQB3hoGEIxeM7x2ZPASC
"""

import os
SKILL = "incident-postmortem"
os.makedirs(f"{SKILL}/scripts", exist_ok=True)

skill_md = r'''---
name: incident-postmortem
description: Generate blameless, consistently formatted production incident post-mortems (RCAs / incident retrospectives) for SRE/DevOps teams. Use this skill whenever the user wants to write up an incident, outage, or production issue, including phrases like "write a post-mortem", "do an RCA", "incident retrospective", "review this outage", or whenever they share an incident timeline and want it turned into a report. Computes exact timing metrics (TTD, TTA, TTM, TTR, customer-impact duration), classifies severity, and enforces blameless language and trackable action items.
---

# Incident Post-Mortem Generator

Turns an incident timeline into a blameless post-mortem. Hand-written ones are
inconsistent: miscomputed metrics, missing sections, blameful language, untrackable
action items. This skill makes the output uniform and the metrics exact.

## Workflow
1. Get a timeline of events. The phases that drive metrics are: incident_start,
   detected, acknowledged, mitigated, resolved.
2. Normalize to JSON: each entry is
   {"ts": "<ISO-8601 UTC>", "type": "<event type>", "note": "<what happened>"}.
3. Compute metrics with the script, never by hand:
   python scripts/incident_metrics.py <incident.json> --pretty
   Use the returned numbers verbatim; surface any warnings to the user.
4. Classify severity: the script gives a hint, but pick the most severe level any
   factor justifies (blast radius, data, security, revenue path), not just duration.
   SEV1 outage/data loss/security; SEV2 major or revenue-path (checkout/payments);
   SEV3 minor; SEV4 cosmetic.
5. Write the report with these sections: Summary, Impact, Timeline, Key metrics,
   Root cause, What went well, What went poorly, Action items.

## Blameless rules (non-negotiable)
- Describe systems and conditions, not culprits ("the deploy lacked an alarm", not
  "Priya forgot the alarm"). Prefer roles over names.
- No blame/shame/hindsight ("should have known", "careless").
- Root cause is a chain of contributing factors, rarely a single human error.

## Action-item rules
Every action item must be specific, owned, dated, and tracked, tagged with a type
(prevent / detect / mitigate / process).
- Bad: "Be more careful with deploys."
- Good: "Add a connection-pool-exhaustion alarm (prevent, owner: Checkout, due: 2026-06-30, PAGE-1183)."
'''

with open(f"{SKILL}/SKILL.md", "w") as f:
    f.write(skill_md)
print("SKILL.md written")

script = r'''#!/usr/bin/env python3
"""Deterministic incident-timeline analyzer. Computes TTD/TTA/TTM/TTR exactly."""
import argparse, json, sys
from datetime import datetime, timezone

PHASES = ["incident_start", "detected", "acknowledged", "mitigated", "resolved"]
SEV_HINT = [(240, "SEV1"), (60, "SEV2"), (15, "SEV3")]  # minutes of customer impact

def parse_ts(raw):
    dt = datetime.fromisoformat(raw.strip().replace("Z", "+00:00"))
    return (dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)).astimezone(timezone.utc)

def human(sec):
    if sec is None: return None
    sec = int(round(sec)); h, rem = divmod(abs(sec), 3600); m, s = divmod(rem, 60)
    p = [f"{h}h"] if h else []
    if m: p.append(f"{m}m")
    if s and not h: p.append(f"{s}s")
    return ("-" if sec < 0 else "") + (" ".join(p) if p else "0m")

def diff(ph, a, b):
    return (ph[b] - ph[a]).total_seconds() if a in ph and b in ph else None

def compute(data):
    ph = {}
    for e in data["timeline"]:
        t = e.get("type")
        if t not in PHASES: continue
        if t in ph: raise ValueError(f"duplicate '{t}' event")
        ph[t] = parse_ts(e["ts"])
    warnings, present = [], [e for e in PHASES if e in ph]
    for a, b in zip(present, present[1:]):
        if ph[a] > ph[b]: warnings.append(f"'{b}' occurs before '{a}'")
    for req in ("detected", "mitigated"):
        if req not in ph: warnings.append(f"missing '{req}' event")
    start, end = ph.get("incident_start", ph.get("detected")), ph.get("mitigated")
    impact = (end - start).total_seconds() if start and end else None
    metrics = {
        "ttd": diff(ph, "incident_start", "detected"),
        "tta": diff(ph, "detected", "acknowledged"),
        "ttm": diff(ph, "detected", "mitigated"),
        "ttr": diff(ph, "detected", "resolved"),
        "customer_impact": impact,
    }
    sev = "SEV4"
    if impact is not None:
        for thr, s in SEV_HINT:
            if impact / 60 >= thr: sev = s; break
    return {
        "incident_id": data.get("incident_id"), "title": data.get("title"),
        "metrics_human": {k: human(v) for k, v in metrics.items()},
        "severity_hint": sev, "warnings": warnings,
    }

def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("incident_file"); ap.add_argument("--pretty", action="store_true")
    a = ap.parse_args(argv)
    try:
        with open(a.incident_file) as fh: data = json.load(fh)
        out = compute(data)
    except (OSError, ValueError, json.JSONDecodeError) as e:
        print(json.dumps({"error": str(e)}), file=sys.stderr); return 1
    print(json.dumps(out, indent=2 if a.pretty else None)); return 0

if __name__ == "__main__":
    raise SystemExit(main())
'''

with open(f"{SKILL}/scripts/incident_metrics.py", "w") as f:
    f.write(script)
print("incident_metrics.py written")

sample = '''{
  "incident_id": "INC-2031",
  "title": "Checkout latency spike",
  "timeline": [
    {"ts": "2026-06-18T14:02:00Z", "type": "incident_start"},
    {"ts": "2026-06-18T14:09:00Z", "type": "detected"},
    {"ts": "2026-06-18T14:12:00Z", "type": "acknowledged"},
    {"ts": "2026-06-18T14:41:00Z", "type": "mitigated"},
    {"ts": "2026-06-18T16:05:00Z", "type": "resolved"}
  ]
}'''
with open(f"{SKILL}/sample-incident.json", "w") as f:
    f.write(sample)

!cd {SKILL} && python scripts/incident_metrics.py sample-incident.json --pretty

import shutil
from google.colab import files
shutil.make_archive("incident-postmortem", "zip", ".", SKILL)
files.download("incident-postmortem.zip")

