# -*- coding: utf-8 -*-
"""factscore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kA91jOGKxDmP1m_bLqylalDA1TtjK_Mp
"""

!pip install -q sentence-transformers numpy nltk

import numpy as np
import nltk
from sentence_transformers import SentenceTransformer

nltk.download('punkt')
from nltk.tokenize import sent_tokenize

# Load embedding model
model = SentenceTransformer("all-MiniLM-L6-v2")

# Knowledge base (retrieved context)
knowledge_base = [
    "A savings account is a bank account that earns interest on deposits.",
    "A current account is used for frequent transactions like business payments.",
    "Fixed deposits lock money for a fixed period with higher interest rates.",
    "Banks provide loans that must be repaid with interest."
]

kb_embeddings = model.encode(knowledge_base)

#  LLM-generated answer
answer = """
A savings account is used to store money safely and earn interest.
It is mainly used for daily business transactions.
"""

import nltk

nltk.download('punkt', force=True)
nltk.download('punkt_tab', force=True)
nltk.download('stopwords')

def factscore(answer, kb_embeddings, threshold=0.65):
    sentences = sent_tokenize(answer)
    sent_embeddings = model.encode(sentences)

    supported = 0
    total = len(sentences)

    for sent_emb in sent_embeddings:
        sims = np.dot(kb_embeddings, sent_emb) / (
            np.linalg.norm(kb_embeddings, axis=1) * np.linalg.norm(sent_emb)
        )

        if np.max(sims) >= threshold:
            supported += 1

    return supported / total if total > 0 else 0


score = factscore(answer, kb_embeddings)

print("FactScore:", round(score, 3))

#  Hallucination check
if score >= 0.8:
    print(" Low hallucination")
elif score >= 0.6:
    print("Medium hallucination risk")
else:
    print("High hallucination detected")

