# -*- coding: utf-8 -*-
"""middleware_observability

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13FYEDvK9owPByibIfNVlfOzkk63oLv7E
"""

# """demo1_middleware_observability.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1YQsWZpmPrif90AZvv0GYzQqOgBhS2Y8o

# # 🔬 Demo 1 — FastAPI Middleware & Observability
# > **EY Backend Engineering Bootcamp — Day 9**

# **Scenario:** You are an EY backend engineer on a global payments modernisation project. In this demo you will build and test the four middleware pillars — Logging, Metrics, Retry, and Circuit Breaker — that every production FastAPI service must have.

# ---
# ### Learning Objectives
# - Attach HTTP middleware to a FastAPI app (logging + metrics)
# - Use `structlog` for structured JSON logging with correlation IDs
# - Expose a `/metrics` endpoint for Prometheus scraping
# - Implement exponential-backoff retry with `tenacity`
# - Implement a circuit breaker with `pybreaker`

# ### 🗺️ Road Map
# ```
# Part 1 → Install deps
# Part 2 → Logging middleware
# Part 3 → Prometheus metrics middleware
# Part 4 → Retry with tenacity
# Part 5 → Circuit breaker with pybreaker
# Part 6 → Run the full app (ngrok tunnel)
# Extension Tasks →  Advanced challenges
# ```

# Commented out IPython magic to ensure Python compatibility.
# ## Part 1 — Install Dependencies
# 
# 
# # Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install fastapi uvicorn[standard] structlog tenacity pybreaker \
#               prometheus-client prometheus-fastapi-instrumentator \
#               httpx pyngrok nest-asyncio

import nest_asyncio
nest_asyncio.apply()  # Allow asyncio inside Colab's event loop
print('✅ Dependencies installed and asyncio patched')
print("successful")

"""---
## Part 2 — Structured Logging Middleware

Every request must carry a **correlation ID** so you can trace a single payment across 50 microservices.
We attach middleware that:
1. Reads `X-Correlation-Id` from the incoming request (or generates a new UUID)
2. Logs request start / end as structured JSON
3. Passes the correlation ID forward in the response
"""

import structlog, logging, uuid, time
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

# Configure structlog to output clean JSON
structlog.configure(
    processors=[
        structlog.stdlib.add_log_level,
        structlog.stdlib.add_logger_name,
        structlog.processors.TimeStamper(fmt='iso'),
        structlog.processors.JSONRenderer()
    ],
    wrapper_class=structlog.BoundLogger,
    logger_factory=structlog.PrintLoggerFactory(),
)

log = structlog.get_logger()

app = FastAPI(title='EY Payment API', version='1.0.0')

@app.middleware('http')
async def logging_middleware(request: Request, call_next):
    correlation_id = request.headers.get('X-Correlation-Id', str(uuid.uuid4()))
    start = time.perf_counter()

    log.info('request.started',
             path=request.url.path,
             method=request.method,
             correlation_id=correlation_id)

    response = await call_next(request)
    elapsed_ms = round((time.perf_counter() - start) * 1000, 2)

    log.info('request.completed',
             path=request.url.path,
             status=response.status_code,
             latency_ms=elapsed_ms,
             correlation_id=correlation_id)

    response.headers['X-Correlation-Id'] = correlation_id
    return response

@app.get('/health/live')
async def liveness():
    return {'status': 'alive'}

@app.get('/health/ready')
async def readiness():
    # In production, check DB + MQ here
    return {'status': 'ready', 'db': 'ok', 'mq': 'ok'}

@app.post('/payments')
async def create_payment(request: Request):
    body = await request.json()
    log.info('payment.received', amount=body.get('amount'), currency=body.get('currency', 'GBP'))
    return {'payment_id': str(uuid.uuid4()), 'status': 'accepted', **body}

print('✅ Logging middleware and routes defined')

"""---
## Part 3 — Prometheus Metrics Middleware

The four golden signals: **Latency, Traffic, Errors, Saturation**. We track all four with Prometheus counters and histograms.
"""

from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST
from prometheus_fastapi_instrumentator import Instrumentator
from fastapi.responses import Response

# Custom business metric: track payment amounts by currency
PAYMENT_AMOUNT = Histogram(
    'payment_amount_gbp', 'Payment amount in GBP',
    buckets=[10, 50, 100, 500, 1000, 5000, 10000]
)

ERROR_COUNT = Counter(
    'payment_errors_total', 'Total payment processing errors',
    ['error_type']
)

# Auto-instrument all HTTP routes (latency, status codes, method)
Instrumentator().instrument(app).expose(app)

print('✅ Prometheus metrics instrumented')
print('   → /metrics endpoint is now available')
print('   → Tracking: request_count, request_latency, payment_amount')

"""---
## Part 4 — Retry Logic with Tenacity

Payment APIs are flaky under load. We use `tenacity` to retry failed calls with **exponential backoff + jitter** to avoid the thundering herd problem.
"""

import random
import asyncio
from tenacity import (
    retry, stop_after_attempt, wait_exponential,
    retry_if_exception_type, before_sleep_log
)

# Simulate a flaky downstream fraud-check service
call_count = 0

async def flaky_fraud_check(payload: dict) -> dict:
    global call_count
    call_count += 1
    # Fail the first 2 attempts, succeed on 3rd
    if call_count < 3:
        print(f'  ⚠️  Attempt {call_count}: fraud API timeout (simulated)')
        raise ConnectionError(f'Fraud API timeout on attempt {call_count}')
    print(f'  ✅ Attempt {call_count}: fraud check passed')
    return {'fraud_score': 0.02, 'decision': 'approved'}


@retry(
    stop=stop_after_attempt(5),
    wait=wait_exponential(multiplier=1, min=0.1, max=2),  # seconds (small for demo)
    retry=retry_if_exception_type((ConnectionError, TimeoutError)),
    reraise=True
)
async def call_fraud_api_with_retry(payload: dict) -> dict:
    return await flaky_fraud_check(payload)


# Test it
print('🔄 Testing retry logic...')
result = asyncio.run(
    call_fraud_api_with_retry({'amount': 1500, 'currency': 'GBP'})
)
print(f'\n📦 Final result: {result}')

"""---
## Part 5 — Circuit Breaker with PyBreaker

If a downstream service is consistently failing, retrying indefinitely makes things **worse**. The circuit breaker trips after `N` failures and returns a fast fallback for 30 seconds — preventing cascade failures.
"""

import pybreaker

class LoggingListener(pybreaker.CircuitBreakerListener):
    def state_change(self, cb, old_state, new_state):
        log.warning('circuit_breaker.state_change',
                    breaker=cb.name,
                    old=str(old_state),
                    new=str(new_state))

fraud_breaker = pybreaker.CircuitBreaker(
    fail_max=3,
    reset_timeout=30,
    listeners=[LoggingListener()],
    name='fraud-api'
)

def check_fraud_cb(payload: dict) -> dict:
    """Wrapped by circuit breaker — raises CircuitBreakerError when OPEN."""
    # Simulate always-failing service for demo
    raise ConnectionError('Fraud service down')

def safe_fraud_check(payload: dict) -> dict:
    """Call fraud API with circuit breaker; return fallback if circuit is OPEN."""
    try:
        return fraud_breaker.call(check_fraud_cb, payload)
    except pybreaker.CircuitBreakerError:
        print('🔴 Circuit OPEN — returning safe fallback (manual review)')
        return {'fraud_score': None, 'decision': 'manual_review', 'circuit': 'open'}
    except Exception as e:
        return {'fraud_score': None, 'decision': 'error', 'reason': str(e)}

print('📊 Simulating calls to a failing fraud service...')
for i in range(6):
    result = safe_fraud_check({'amount': 200 * (i + 1)})
    print(f'  Call {i+1}: {result} | Circuit state: {fraud_breaker.current_state}')

"""---
## Part 6 — Run the Full App

We start uvicorn in the background and expose it via a public ngrok tunnel so you can hit it from your browser or Postman.
"""

# ⚠️ You need a free ngrok account. Get your token at https://dashboard.ngrok.com
NGROK_TOKEN = 'PASTE_YOUR_TOKEN_HERE'  # ← replace this

import threading, uvicorn
from pyngrok import ngrok, conf

conf.get_default().auth_token = NGROK_TOKEN

def run_server():
    uvicorn.run(app, host='0.0.0.0', port=8000, log_level='warning')

thread = threading.Thread(target=run_server, daemon=True)
thread.start()

import time; time.sleep(2)
tunnel = ngrok.connect(8000)
public_url = tunnel.public_url

print(f'🌐 Public URL: {public_url}')
print(f'   Health:   {public_url}/health/ready')
print(f'   Metrics:  {public_url}/metrics')
print(f'   Docs:     {public_url}/docs')

# Quick smoke tests using httpx
import httpx, json

BASE = public_url  # set in the cell above

with httpx.Client() as client:
    # 1 — Health check
    r = client.get(f'{BASE}/health/ready')
    print('Health:', r.json())

    # 2 — POST a payment (watch structured logs above)
    r = client.post(f'{BASE}/payments',
                    json={'amount': 1500, 'currency': 'GBP', 'account': 'ACC-42'},
                    headers={'X-Correlation-Id': 'demo-corr-001'})
    print('Payment:', r.json())
    print('Returned correlation ID:', r.headers.get('X-Correlation-Id'))

    # 3 — Peek at first 500 chars of /metrics
    r = client.get(f'{BASE}/metrics')
    print('\nMetrics (first 500 chars):')
    print(r.text[:500])

# ## 🔥 Extension Tasks

# ### Extension A — Rate-Limiting Middleware *(Medium)*
# Add a sliding-window rate limiter (e.g., 100 req/min per client IP) using an in-memory dictionary.
# - Return `429 Too Many Requests` with a `Retry-After` header when the limit is exceeded
# - Track limit hits as a Prometheus `Counter`

from collections import defaultdict, deque
from prometheus_client import Counter

RATE_LIMIT_HITS = Counter(
    "rate_limit_hits_total",
    "Total rate limit violations"
)

from time import time

RATE_LIMIT = 100          # requests
WINDOW_SECONDS = 60       # per minute

request_store = defaultdict(deque)

from fastapi.responses import JSONResponse

@app.middleware("http")
async def rate_limit_middleware(request: Request, call_next):

    client_ip = request.client.host
    now = time()

    bucket = request_store[client_ip]

    # Remove expired timestamps
    while bucket and bucket[0] < now - WINDOW_SECONDS:
        bucket.popleft()

    if len(bucket) >= RATE_LIMIT:
        RATE_LIMIT_HITS.inc()

        retry_after = int(WINDOW_SECONDS - (now - bucket[0]))

        return JSONResponse(
            status_code=429,
            content={"detail": "Rate limit exceeded"},
            headers={"Retry-After": str(retry_after)}
        )

    bucket.append(now)

    return await call_next(request)

# ### Extension B — Correlation ID Propagation *(Medium)*
# The current middleware assigns a correlation ID but does NOT forward it to outbound `httpx` calls.
# - Add a `contextvars.ContextVar` to store the correlation ID per request
# - Write a custom `httpx.Auth` or event hook that injects `X-Correlation-Id` into every outbound call
# - Verify it appears in mock downstream requests

# ===================================
# EXTENSION B
# Correlation ID Propagation
# ===================================

import contextvars
import httpx
import uuid
from fastapi import Request

# Store correlation ID per request
correlation_id_ctx = contextvars.ContextVar(
    "correlation_id",
    default=None
)

# Replace previous middleware with this version
@app.middleware("http")
async def correlation_logging_middleware(
    request: Request,
    call_next
):
    correlation_id = request.headers.get(
        "X-Correlation-Id",
        str(uuid.uuid4())
    )

    correlation_id_ctx.set(correlation_id)

    response = await call_next(request)

    response.headers["X-Correlation-Id"] = correlation_id
    return response


# Inject correlation ID into every outbound request
async def add_correlation_id(request: httpx.Request):
    cid = correlation_id_ctx.get()

    if cid:
        request.headers["X-Correlation-Id"] = cid


http_client = httpx.AsyncClient(
    event_hooks={
        "request": [add_correlation_id]
    }
)

# Demo endpoint
@app.get("/propagation-test")
async def propagation_test():

    response = await http_client.get(
        "https://httpbin.org/headers"
    )

    return response.json()

print("✅ Correlation ID propagation enabled")
print("   Test endpoint: /propagation-test")

# ### Extension C — Prometheus + Grafana Dashboard *(Advanced)*
# - Export your running `/metrics` to a free [Grafana Cloud](https://grafana.com/products/cloud/) account using the Prometheus remote-write endpoint
# - Build a dashboard with 4 panels: request rate, p99 latency, error rate, circuit breaker trip count


# ===================================
# EXTENSION C
# Grafana Dashboard Metrics
# ===================================

from prometheus_client import Counter

# Track circuit breaker trips
CIRCUIT_BREAKER_TRIPS = Counter(
    "circuit_breaker_trips_total",
    "Total circuit breaker trips"
)

# Enhanced listener
class GrafanaLoggingListener(pybreaker.CircuitBreakerListener):

    def state_change(self, cb, old_state, new_state):

        log.warning(
            "circuit_breaker.state_change",
            breaker=cb.name,
            old=str(old_state),
            new=str(new_state)
        )

        if str(new_state).lower().endswith("open"):
            CIRCUIT_BREAKER_TRIPS.inc()

# Replace existing breaker
fraud_breaker = pybreaker.CircuitBreaker(
    fail_max=3,
    reset_timeout=30,
    listeners=[GrafanaLoggingListener()],
    name="fraud-api"
)

print("✅ Grafana metrics ready")
print("\nUse these PromQL queries in Grafana:\n")

print("1. Request Rate")
print("rate(http_requests_total[5m])\n")

print("2. P99 Latency")
print("""
histogram_quantile(
  0.99,
  sum(rate(http_request_duration_seconds_bucket[5m])) by (le)
)
""")

print("3. Error Rate")
print("rate(payment_errors_total[5m])\n")

print("4. Circuit Breaker Trips")
print("rate(circuit_breaker_trips_total[5m])")

# ### Extension D — Structured Log Aggregation *(Advanced)*
# - Set up a free [Elastic Cloud](https://www.elastic.co/cloud/) cluster or use the Colab local filesystem
# - Configure `structlog` to write logs as newline-delimited JSON to a file
# - Write a query that finds all requests with `latency_ms > 200` for a specific `correlation_id`



# ===================================
# EXTENSION D
# Structured Log Aggregation
# ===================================

import json

# Create sample NDJSON log file
sample_logs = [
    {
        "event": "request.completed",
        "correlation_id": "abc123",
        "latency_ms": 312,
        "status": 200
    },
    {
        "event": "request.completed",
        "correlation_id": "xyz789",
        "latency_ms": 80,
        "status": 200
    },
    {
        "event": "request.completed",
        "correlation_id": "abc123",
        "latency_ms": 450,
        "status": 500
    }
]

with open("payments.ndjson", "w") as f:
    for log in sample_logs:
        f.write(json.dumps(log) + "\n")

print("✅ payments.ndjson created")

# Query logs
print("\n🔍 Slow requests (>200ms) for correlation_id='abc123'\n")

with open("payments.ndjson", "r") as f:
    for line in f:
        record = json.loads(line)

        if (
            record.get("correlation_id") == "abc123"
            and record.get("latency_ms", 0) > 200
        ):
            print(record)

print("\n✅ Log aggregation demo completed")

