# -*- coding: utf-8 -*-
"""flask_app_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tU8ZGytW2Qy5hCaHYBYR4Wkwk07mX8G-
"""

!pip install flask pydantic structlog pytest pyngrok

from flask import Flask, Blueprint, request, jsonify, g
from pydantic import BaseModel, ValidationError
from typing import List
import uuid
import time
import structlog
from werkzeug.exceptions import HTTPException

# --------------------
# Structured Logging
# --------------------

structlog.configure(
    processors=[
        structlog.processors.TimeStamper(fmt="iso"),
        structlog.processors.JSONRenderer()
    ]
)

logger = structlog.get_logger()

# --------------------
# Pydantic Models
# --------------------

class PredictionRequest(BaseModel):
    features: List[float]

class PredictionResponse(BaseModel):
    id: str
    prediction: float

# --------------------
# In-memory storage
# --------------------

PREDICTIONS = {}

# --------------------
# Blueprint
# --------------------

api = Blueprint("api", __name__)

@api.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "healthy"})


@api.route("/predictions", methods=["POST"])
def create_prediction():

    try:
        payload = PredictionRequest(**request.json)

    except ValidationError as e:
        return jsonify({
            "errors": e.errors()
        }), 422

    prediction_id = str(uuid.uuid4())

    prediction = sum(payload.features)

    response = PredictionResponse(
        id=prediction_id,
        prediction=prediction
    )

    PREDICTIONS[prediction_id] = response

    return jsonify(response.model_dump()), 201


@api.route("/predictions/<prediction_id>", methods=["GET"])
def get_prediction(prediction_id):

    result = PREDICTIONS.get(prediction_id)

    if not result:
        return jsonify({
            "error": "Prediction not found"
        }), 404

    return jsonify(result.model_dump())


# --------------------
# App Factory
# --------------------

def create_app():

    app = Flask(__name__)

    @app.before_request
    def before_request():

        g.start_time = time.time()
        g.correlation_id = str(uuid.uuid4())

    @app.after_request
    def after_request(response):

        duration = round(
            (time.time() - g.start_time) * 1000,
            2
        )

        logger.info(
            "request_completed",
            correlation_id=g.correlation_id,
            method=request.method,
            path=request.path,
            status=response.status_code,
            duration_ms=duration
        )

        return response

    app.register_blueprint(api)

    # Error Handlers

    @app.errorhandler(404)
    def not_found(error):
        return jsonify({
            "error": "Not Found"
        }), 404

    @app.errorhandler(500)
    def internal(error):
        return jsonify({
            "error": "Internal Server Error"
        }), 500

    return app


app = create_app()

from threading import Thread

def run():
    app.run(host="0.0.0.0", port=5000)

thread = Thread(target=run)
thread.start()

import requests

response = requests.get(
    "http://127.0.0.1:5000/health"
)

print(response.status_code)
print(response.json())

response = requests.post(
    "http://127.0.0.1:5000/predictions",
    json={"features":[1,2,3]}
)

print(response.status_code)
print(response.json())

import requests

payload = {
    "features": [10, 20, 30]
}

response = requests.post(
    "http://127.0.0.1:5000/predictions",
    json=payload
)

print(response.status_code)
print(response.json())

import requests

bad_payload = {
    "features": "invalid_data_type"
}

response = requests.post(
    "http://127.0.0.1:5000/predictions",
    json=bad_payload
)

print("Status Code:", response.status_code)
print(response.json())

from pydantic import BaseModel

class PredictionResponseModel(BaseModel):
    id: str
    prediction: float

validated_response = PredictionResponseModel(
    **prediction_data
)

print(validated_response)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test_api.py
# 
# import requests
# 
# BASE_URL = "http://127.0.0.1:5000"
# 
# def test_health():
# 
#     response = requests.get(
#         f"{BASE_URL}/health"
#     )
# 
#     assert response.status_code == 200
# 
# 
# def test_invalid_payload():
# 
#     response = requests.post(
#         f"{BASE_URL}/predictions",
#         json={
#             "features": "invalid"
#         }
#     )
# 
#     assert response.status_code == 422