# -*- coding: utf-8 -*-
"""groundedness_usefulness.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1CCy5bdw7YVxhLS4NtrWLYer18TEygy
"""

# ==========================================================
# EXTENSION TASK:
# USEFULNESS + GROUNDEDNESS EVALUATION
# ==========================================================

GROUND_SCORES = []
USEFUL_SCORES = []

def groundedness_score(source_text, summary):
    """
    Measures how much of the summary
    is supported by the source text.
    """

    source_words = set(source_text.lower().split())
    summary_words = set(summary.lower().split())

    if len(summary_words) == 0:
        return 0.0

    overlap = len(
        source_words.intersection(summary_words)
    )

    return round(
        overlap / len(summary_words),
        2
    )


def usefulness_score(summary):
    """
    Measures business usefulness
    of generated summary.
    """

    keywords = [
        "industry",
        "company",
        "market",
        "customer",
        "growth",
        "revenue",
        "strategy",
        "product",
        "service",
        "opportunity"
    ]

    summary = summary.lower()

    score = sum(
        1 for word in keywords
        if word in summary
    )

    return round(
        score / len(keywords),
        2
    )


def evaluate_summary(source_text, summary):

    grounded = groundedness_score(
        source_text,
        summary
    )

    useful = usefulness_score(
        summary
    )

    final_score = round(
        (grounded + useful) / 2,
        2
    )

    GROUND_SCORES.append(
        grounded
    )

    USEFUL_SCORES.append(
        useful
    )

    return {
        "groundedness": grounded,
        "usefulness": useful,
        "final_score": final_score
    }


# ==========================================================
# SAMPLE TEST
# Replace source_text and summary with your pipeline outputs
# ==========================================================

source_text = """
Acme Corp is a software company.
The company provides AI products for enterprises.
Revenue grew 25 percent this year.
Customers increased across healthcare and finance sectors.
"""

summary = """
Acme Corp is a growing AI software company.
Revenue increased and customer adoption expanded.
The company has strong market opportunities.
"""

scores = evaluate_summary(
    source_text,
    summary
)

print("=" * 50)
print("QUALITY EVALUATION")
print("=" * 50)

print(
    "Groundedness :",
    scores["groundedness"]
)

print(
    "Usefulness   :",
    scores["usefulness"]
)

print(
    "Final Score  :",
    scores["final_score"]
)

print("\nAVERAGE METRICS")

print(
    "Avg Groundedness:",
    round(
        sum(GROUND_SCORES) /
        len(GROUND_SCORES),
        2
    )
)

print(
    "Avg Usefulness:",
    round(
        sum(USEFUL_SCORES) /
        len(USEFUL_SCORES),
        2
    )
)

"""Implemented Groundedness and Usefulness evaluation for generated summaries.

Groundedness measures whether generated content is supported by the source text using token overlap.

Usefulness measures the presence of business-relevant information such as revenue, market, customer, growth and strategy insights.

Telemetry records groundedness, usefulness and final quality score for monitoring summary quality.
"""