# -*- coding: utf-8 -*-
"""Multi_part_upload.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vB0lWTANVaSKbMNxC59eY2Pa9XcSHsvS
"""

import random
import time
import uuid
import json
from datetime import datetime


def now():
    return datetime.utcnow().isoformat() + "Z"


class Telemetry:
    def __init__(self, total_steps):
        self.trace_id = str(uuid.uuid4())
        self.total_steps = total_steps
        self.completed_steps = 0
        self.run_start = time.time()
        self.completed_agents = []
        self.failed_agent = None

    def emit(self, event):
        print(json.dumps(event))

    def progress_metrics(self):
        elapsed = max(time.time() - self.run_start, 0.001)

        return {
            "pipeline_percent_complete": round(
                (self.completed_steps / self.total_steps) * 100, 2
            ),
            "throughput_steps_per_sec": round(
                self.completed_steps / elapsed, 2
            ),
        }


class Agent:
    def __init__(self, name, steps, fail_at_step=None):
        self.name = name
        self.steps = steps
        self.fail_at_step = fail_at_step

    def run(self, telemetry):
        span_id = str(uuid.uuid4())

        agent_start = time.time()

        telemetry.emit({
            "timestamp": now(),
            "trace_id": telemetry.trace_id,
            "span_id": span_id,
            "event": "agent_started",
            "agent": self.name
        })

        checkpoints = {
            max(1, round(self.steps * 0.25)),
            max(1, round(self.steps * 0.50)),
            max(1, round(self.steps * 0.75)),
            self.steps
        }

        for step in range(1, self.steps + 1):

            time.sleep(random.uniform(0.05, 0.2))

            if self.fail_at_step and step == self.fail_at_step:
                metrics = telemetry.progress_metrics()

                telemetry.emit({
                    "timestamp": now(),
                    "trace_id": telemetry.trace_id,
                    "span_id": span_id,
                    "event": "agent_failed",
                    "agent": self.name,
                    "step": step,
                    "error": f"{self.name} failed at step {step}",
                    **metrics
                })

                raise RuntimeError(
                    f"{self.name} failed at step {step}"
                )

            telemetry.completed_steps += 1

            if step in checkpoints:
                metrics = telemetry.progress_metrics()

                telemetry.emit({
                    "timestamp": now(),
                    "trace_id": telemetry.trace_id,
                    "span_id": span_id,
                    "event": "agent_progress",
                    "agent": self.name,
                    "step": step,
                    "total_steps": self.steps,
                    **metrics
                })

        duration = round(time.time() - agent_start, 2)

        telemetry.completed_agents.append(self.name)

        telemetry.emit({
            "timestamp": now(),
            "trace_id": telemetry.trace_id,
            "span_id": span_id,
            "event": "agent_completed",
            "agent": self.name,
            "duration_seconds": duration,
            **telemetry.progress_metrics()
        })


class Orchestrator:
    def __init__(self, agents):
        self.agents = agents

    def run(self):
        total_steps = sum(agent.steps for agent in self.agents)

        telemetry = Telemetry(total_steps)

        status = "SUCCESS"

        try:
            for agent in self.agents:
                agent.run(telemetry)

        except Exception as e:
            status = "FAILED"
            telemetry.failed_agent = agent.name

        total_duration = round(
            time.time() - telemetry.run_start,
            2
        )

        telemetry.emit({
            "timestamp": now(),
            "trace_id": telemetry.trace_id,
            "event": "run_summary",
            "status": status,
            "total_duration_seconds": total_duration,
            "agents_completed": telemetry.completed_agents,
            "failed_agent": telemetry.failed_agent,
            "pipeline_percent_complete":
                round(
                    (telemetry.completed_steps /
                     telemetry.total_steps) * 100,
                    2
                )
        })


def main():

    agents = [
        Agent("Planner", 3),
        Agent("Researcher", 6),
        Agent("Writer", 4),
        Agent("Reviewer", 2)

        # Failure test:
        # Agent("Writer", 4, fail_at_step=3)
    ]

    Orchestrator(agents).run()


if __name__ == "__main__":
    main()

"""In a production multi-agent workflow, I would additionally capture token usage, tool-call latency, retry counts, and cost per agent. These events would be exported to an observability platform such as OpenTelemetry, Datadog, ELK Stack, or CloudWatch to support tracing, alerting, and root-cause analysis."""

