# -*- coding: utf-8 -*-
"""Video_audio_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0rMuaHyJ2C191Lt6BzmK6oi0P-uTD8I
"""

!apt-get install -q -y ffmpeg nodejs
!pip install -q yt-dlp openai-whisper
!ln -sf /usr/bin/nodejs /usr/local/bin/node
!node --version
!ffmpeg -version | head -1

from google.colab import files
import os

uploaded = files.upload()
for filename, data in uploaded.items():
    with open("/content/cookies.txt", "wb") as f:
        f.write(data)
    print(f"✅ Saved ({len(data)} bytes)")

import os, glob, whisper
from yt_dlp import YoutubeDL
from google.colab import files

OUTPUT_DIR = "/content/output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

def run(url, model_size="base", cookies_file="/content/cookies.txt"):

    # ── 1. Download ──────────────────────────────────────────
    print("📥 Downloading audio...")
    ydl_opts = {
        "format"            : "bestaudio/best",
        "outtmpl"           : f"{OUTPUT_DIR}/%(id)s.%(ext)s",
        "nocheckcertificate": True,
        "quiet"             : False,
        "cookiefile"        : cookies_file,
        "postprocessors"    : [{
            "key"             : "FFmpegExtractAudio",
            "preferredcodec"  : "mp3",
            "preferredquality": "192",
        }],
    }

    with YoutubeDL(ydl_opts) as ydl:
        info     = ydl.extract_info(url, download=True)
        video_id = info.get("id", "audio")
        title    = info.get("title", video_id)
        duration = info.get("duration", 0)

    # Find the mp3
    audio_path = f"{OUTPUT_DIR}/{video_id}.mp3"
    if not os.path.exists(audio_path):
        mp3s = sorted(glob.glob(f"{OUTPUT_DIR}/*.mp3"), key=os.path.getmtime)
        if not mp3s:
            raise FileNotFoundError("No mp3 found. Check ffmpeg is installed.")
        audio_path = mp3s[-1]

    print(f"✅ Downloaded : {title} ({duration}s)")

    # ── 2. Transcribe ────────────────────────────────────────
    print(f"\n🧠 Loading Whisper '{model_size}' model...")
    model  = whisper.load_model(model_size)
    print("🎙️  Transcribing... (may take a minute)\n")
    result = model.transcribe(audio_path, fp16=False, verbose=False)

    # ── 3. Print output ──────────────────────────────────────
    text     = result.get("text", "").strip()
    language = result.get("language", "unknown")
    segments = result.get("segments", [])

    print("="*60)
    print("  TRANSCRIPTION RESULT")
    print("="*60)
    print(f"  Video    : {title}")
    print(f"  Language : {language}")
    print(f"  Segments : {len(segments)}")
    print("-"*60)
    print(text)
    print("="*60)

    print("\n  TIMED SEGMENTS")
    print("-"*60)
    for seg in segments:
        print(f"  [{seg['start']:6.1f}s → {seg['end']:6.1f}s]  {seg['text'].strip()}")

    # ── 4. Save files ────────────────────────────────────────
    safe     = "".join(c if c.isalnum() or c in " _-" else "_" for c in title)
    txt_path = f"{OUTPUT_DIR}/{safe}.txt"
    srt_path = f"{OUTPUT_DIR}/{safe}.srt"

    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(text)

    def fmt(s):
        h, m = int(s//3600), int((s%3600)//60)
        return f"{h:02d}:{m:02d}:{int(s%60):02d},{int((s-int(s))*1000):03d}"

    with open(srt_path, "w", encoding="utf-8") as f:
        for i, seg in enumerate(segments, 1):
            f.write(f"{i}\n{fmt(seg['start'])} --> {fmt(seg['end'])}\n{seg['text'].strip()}\n\n")

    print(f"\n💾 Transcript : {txt_path}")
    print(f"📄 Subtitles  : {srt_path}")

    # ── 5. Auto download ─────────────────────────────────────
    files.download(txt_path)
    files.download(srt_path)
    print("\n✅ Done!")

run(
    url          = "https://www.youtube.com/watch?v=jNQXAC9IVRw",
    model_size   = "base",
    cookies_file = "/content/cookies.txt"
)

