# -*- coding: utf-8 -*-
"""pymupdf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJJusjc-3o_EH0S7-_h-5Ow67ktBKYC-
"""

pip install pymupdf

import os
import fitz  # pip install pymupdf

# ── Open the PDF ───────────────────────────────────
doc = fitz.open("Day4_coding_Assignment.pdf")

print(f"Pages : {len(doc)}")
print(f"Title : {doc.metadata['title']}")
print(f"Author: {doc.metadata['author']}")

# ── Extract text from every page ───────────────────
for page_num, page in enumerate(doc, start=1):
    text = page.get_text()          # plain UTF-8 string
    print(f"\n── Page {page_num} ──")
    print(text.strip())

doc.close()

